## Sequence Prediction

## Cleaning the data

In [1]:
import numpy as np
import pandas as pd
from keras.layers import Activation,Dense,Dropout
from keras.models import Sequential
from keras.layers import LSTM
import matplotlib.pyplot as plt
%pylab inline

Using Theano backend.


Populating the interactive namespace from numpy and matplotlib


In [2]:
df = pd.read_csv('/home/najeeb/Desktop/Dataset/sequence/train.csv',index_col = 0)
df.info()
df.describe()
df.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 113845 entries, 3 to 227690
Data columns (total 1 columns):
Sequence    113845 non-null object
dtypes: object(1)
memory usage: 1.7+ MB


Sequence
Id                                                   
3   1,3,13,87,1053,28576,2141733,508147108,4021352...
7   1,2,1,5,5,1,11,16,7,1,23,44,30,9,1,47,112,104,...
8   1,2,4,5,8,10,16,20,32,40,64,80,128,160,256,320...
11  1,8,25,83,274,2275,132224,1060067,3312425,1099...
13  1,111,12211,1343211,147753211,16252853211,1787...

In [30]:
eps = 5
X = []
for series in df['Sequence']:
    s = series.split(',')
    if len(s) > eps:
        X.append(s)

In [31]:
print len(X)
y = []

111880


In [32]:
for i in range(len(X)):
    temp = X[i][0:5]
    y.append(int(X[i][5]))
    X[i] = temp

In [33]:
for i in range(len(X)):
    for j in range(len(X[i])):
        X[i][j] = int(X[i][j])

In [34]:
X_train = np.asarray(X[0:80000])
X_test = np.asarray(X[80000:])
print X_train.shape
print X_test.shape

(80000, 5)
(31880, 5)


In [35]:
y_train = np.asarray(y[0:80000])
y_test = np.asarray(y[80000:])
print y_train.shape
print y_test.shape

(80000,)
(31880,)


In [36]:
print X_train[0:10]
print type(X_train)

[[1 3 13 87 1053]
 [1 2 1 5 5]
 [1 2 4 5 8]
 [1 8 25 83 274]
 [1 111 12211 1343211 147753211]
 [1 1 1 1 1]
 [840 1320 1680 2520 3192]
 [1 2 7 27 113]
 [4 6 8 9 26]
 [1 2 1 3 4]]
<type 'numpy.ndarray'>


In [37]:
print y_train[0:10]
print type(y_train)

[28576 1 10 2275 16252853211 1 3432 483 1752 2]
<type 'numpy.ndarray'>


In [38]:
## Reshaping the X_test and X_train array
## LSTM asks for reshaping the array
X_train = np.reshape(X_train,(X_train.shape + (1,)))
X_test = np.reshape(X_test,(X_test.shape + (1,)))
print X_train.shape,X_test.shape

(80000, 5, 1) (31880, 5, 1)


## Recurrent Neural Network Model
### To predict the next integer of a sequence

In [25]:
model = Sequential()
model.add(LSTM(32,return_sequences = True, input_shape = np.shape(X_train)[1:]))
model.add(Activation('relu'))
model.add(Dropout(0.25))
model.add(LSTM(32,return_sequences = False))
model.add(Activation('relu'))
model.add(Dropout(0.25))
model.add(Dense(1))
model.add(Activation('relu'))

In [26]:
model.compile(loss = 'mse',optimizer = 'adagrad',metrics = ['accuracy'])

In [ ]:
model.fit(X_train,y_train,batch_size=32,nb_epoch = 10,verbose = 1)

In [112]:
model.save_weights('/home/najeeb/Desktop/Dataset/sequence/Weights.hdf5')

In [114]:
score = model.evaluate(X_test,y_test,batch_size=32,verbose = 0)

In [115]:
print score

[nan, 0.0]
